# Site settings
title: "Akhmad Syarif"
email: akhmadsyarif04.arif@gmail.com
description: "This my blog for you."
baseurl: "/blog"
url: ""
title_description: "`Doing Your Best Means Never Stop Trying`"
title_image: "https://cdn140.picsart.com/266036403011211.png?r1024x1024"
google_analytics: "UA-20365477-4"
disqus_account: akhmadsyarif
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  akhmadsyarif04
instagram_username: a.syarif04
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: akhmad syarif

# Footer
footer_left: "Tamplate Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
